@Restaurants.API_HostAddress = https://localhost:7069
@token = CfDJ8E2Yvhj5sj9HtH-6gZUqmQIHxDfwmkBwr8GGein0Q6dyC5hW_bSreypVFiOgUyqw05qncR7Jx1kaojeCky59Uz7DnkD-umwICAF1I2YNuNYzQp7O3UCy_0EsMFZxoCwzmtENO6-7bph75CjjO2L_F2BJa3KAuJmV49m8k4FvO1XerWNq9LDcIb0LLLVvAiuw_qsn6kCtfVx2n7ZxGpDJGp71d4B20wGWCImwCueGA8E7SIN8jNSol-MjeiFdelGzRUdOLN626ksy7EwI3vBIGxTg06ugarbXBxFY4kl3F2b7yVasPxchk3QmpTiOr_MLblXF0v3VfI0qO6OfuskfJJZLnvvGogVOrB85GiZRF4AR_Ll8FE_wg5WftjU7RNk-yJ8n1JTEhc_M9U7BYI1HV4NiELwlqrTCOkF2YZhjvzA63u6Y9-gKadcsKV0pgGHLQIajuSNzxjP-wMzwidECIdu2xR0nMFZ6GXnNCxku8mREtpfQPU7LQ6UiSL7PisGBdxexO_9kfO4GhxeyV0sHl6tufIrqg4EcjRO3s8p0CVM--BSYeER2_1MkNaPL0YThyTOJ2QJC2fNMZexrFVIaEuEGnFEZQEnJhh9S1n7l_IPrt0sCW-Icp4SiRHAkil0hqmXT7BQRC_E4gPy6FpwlvIB_jG0Hu60de2syY_HdYzeYvZ9u6x6TYcUa0O0bKJcm3Gi9lJvnqUPfeU9joWRZq2VZBmkWd8v6R4Jcic495-mnXl1DulDeT01Wx3pDgroR1BmGwrrR41uND_nuphDh2KwHEtk_oIojnsvDIzKcP57i

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Cafe 16",
  "Description": "A charming cafe offering a cozy atmosphere with a variety of coffees and pastries.",
  "Category": "Japanese",
  "HasDelivery": false,
  "ContactEmail": "hello@cafedelight.com",
  "ContactNumber": "32-16540987",
  "Street": "123 Coffee Lane",
  "City": "San Francisco",
  "PostalCode": "94-102"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/8

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name": "New name",
  "Description": "New description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
  "Name": "New dish",
  "Description": "Description of the new dish.",
  "Price": 5,
  "KiloCalories": 100
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###

@dishId=7
GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password#1"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "admin@test.com",
  "password": "Password#1"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "testuser@test.com",
  "roleName": "User"
}
