@Restaurants.API_HostAddress = https://localhost:7069

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Cafe 6",
  "Description": "A charming cafe offering a cozy atmosphere with a variety of coffees and pastries.",
  "Category": "Japanese",
  "HasDelivery": false,
  "ContactEmail": "hello@cafedelight.com",
  "ContactNumber": "32-16540987",
  "Street": "123 Coffee Lane",
  "City": "San Francisco",
  "PostalCode": "94-102"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/8

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name": "New name",
  "Description": "New description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
  "Name": "New dish",
  "Description": "Description of the new dish.",
  "Price": 5,
  "KiloCalories": 100
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###

@dishId=7
GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes

###
