@Restaurants.API_HostAddress = https://localhost:7069

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Cafe 6",
  "Description": "A charming cafe offering a cozy atmosphere with a variety of coffees and pastries.",
  "Category": "Japanese",
  "HasDelivery": false,
  "ContactEmail": "hello@cafedelight.com",
  "ContactNumber": "32-16540987",
  "Street": "123 Coffee Lane",
  "City": "San Francisco",
  "PostalCode": "94-102"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/7
Content-Type: application/json

{
  "Name": "New name",
  "Description": "New description.",
  "HasDelivery": true
}